"""empty message

Revision ID: 0255a3b9baad
Revises: 17fbe9e218ae
Create Date: 2023-01-29 14:35:45.416330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0255a3b9baad'
down_revision = '17fbe9e218ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_images__gallery')
    with op.batch_alter_table('images__gallery', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER())

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('images__gallery', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_images__gallery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_gallery', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('gallery_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name='fk_images__gallery_gallery_id_gallery'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id'),
    sa.PrimaryKeyConstraint('id', name='pk_images__gallery')
    )
    # ### end Alembic commands ###
