"""simple data doc

Revision ID: 042cffd2ec82
Revises: fad01a3fac5b
Create Date: 2022-08-02 18:37:14.446744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042cffd2ec82'
down_revision = 'fad01a3fac5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.drop_column('batas_sip')
        batch_op.drop_column('hari_praktik')
        batch_op.drop_column('file_ijazah')
        batch_op.drop_column('jam_mulai')
        batch_op.drop_column('file_sip')
        batch_op.drop_column('jam_selesai')
        batch_op.drop_column('kota_praktik')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kota_praktik', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('jam_selesai', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('file_sip', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('jam_mulai', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('file_ijazah', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('hari_praktik', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('batas_sip', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
