"""remove file sip ijazah

Revision ID: 1097503a1ae4
Revises: 27100954581a
Create Date: 2023-02-09 09:46:11.985762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1097503a1ae4'
down_revision = '27100954581a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.drop_column('file_sip')
        batch_op.drop_column('file_ijazah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_ijazah', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_sip', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
