"""empty message

Revision ID: 138e6a4cdebb
Revises: 4dd180bc4c99
Create Date: 2022-08-03 13:28:24.669629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138e6a4cdebb'
down_revision = '4dd180bc4c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btas_sip', sa.Date(), nullable=False))
        batch_op.drop_column('batas_sip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_sip', sa.DATETIME(), nullable=False))
        batch_op.drop_column('btas_sip')

    # ### end Alembic commands ###
