"""add hari_praktik

Revision ID: 19abce7a1323
Revises: 89623f7a680a
Create Date: 2022-08-03 18:45:04.356032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19abce7a1323'
down_revision = '89623f7a680a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hari_praktik', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.drop_column('hari_praktik')

    # ### end Alembic commands ###
