"""empty message

Revision ID: 27100954581a
Revises: a50c48ebd205
Create Date: 2023-02-04 13:06:16.022240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27100954581a'
down_revision = 'a50c48ebd205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_images__gallery')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('response')

    op.create_table('_alembic_tmp_images__gallery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_gallery', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('gallery_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name='fk_images__gallery_gallery_id_gallery'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id'),
    sa.PrimaryKeyConstraint('id', name='pk_images__gallery')
    )
    # ### end Alembic commands ###
