"""Initial migration.

Revision ID: 34d19eb9e801
Revises: d562506a5c5c
Create Date: 2022-08-01 12:58:53.137202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d19eb9e801'
down_revision = 'd562506a5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_dokter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('no_hp', sa.String(length=100), nullable=False),
    sa.Column('kota_praktik', sa.String(length=50), nullable=False),
    sa.Column('alamat_praktik', sa.String(length=200), nullable=False),
    sa.Column('tempat_praktik', sa.String(length=100), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('batas_SIP', sa.DateTime(), nullable=False),
    sa.Column('file_sip', sa.String(length=50), nullable=False),
    sa.Column('file_ijazah', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alamat_praktik'),
    sa.UniqueConstraint('kota_praktik'),
    sa.UniqueConstraint('nama_lengkap'),
    sa.UniqueConstraint('no_hp'),
    sa.UniqueConstraint('tempat_praktik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_dokter')
    # ### end Alembic commands ###
