"""empty message

Revision ID: 5273169ad91e
Revises: 1097503a1ae4
Create Date: 2023-02-09 14:54:21.472618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5273169ad91e'
down_revision = '1097503a1ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempat_praktik')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempat_praktik',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tempat_praktik', sa.VARCHAR(length=100), nullable=False),
    sa.Column('alamat_praktik', sa.VARCHAR(length=200), nullable=False),
    sa.Column('kota_praktik', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hari_praktik', sa.VARCHAR(length=50), nullable=False),
    sa.Column('jam_mulai', sa.TIME(), nullable=False),
    sa.Column('jam_selesai', sa.TIME(), nullable=False),
    sa.Column('datadokter_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['datadokter_id'], ['data_dokter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
