"""empty message

Revision ID: 62f1da770384
Revises: 939b636e8dd2
Create Date: 2022-12-07 08:46:02.831961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f1da770384'
down_revision = '939b636e8dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files__public', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    with op.batch_alter_table('images__gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images__gallery', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('files__public', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
