"""empty message

Revision ID: 89623f7a680a
Revises: 138e6a4cdebb
Create Date: 2022-08-03 13:38:12.045156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89623f7a680a'
down_revision = '138e6a4cdebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_sip', sa.Date(), nullable=False))
        batch_op.drop_column('btas_sip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btas_sip', sa.DATE(), nullable=False))
        batch_op.drop_column('batas_sip')

    # ### end Alembic commands ###
