"""added slug for category

Revision ID: 939b636e8dd2
Revises: 65e24755c59f
Create Date: 2022-08-13 19:31:26.241105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939b636e8dd2'
down_revision = '65e24755c59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))

    with op.batch_alter_table('categoryn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryn', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
