"""add status data chatbot

Revision ID: a50c48ebd205
Revises: 0255a3b9baad
Create Date: 2023-02-04 12:54:07.198678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50c48ebd205'
down_revision = '0255a3b9baad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_data', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('status_data')

    with op.batch_alter_table('images__gallery', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
