"""empty message

Revision ID: c4c83ccf479d
Revises: 5273169ad91e
Create Date: 2023-02-09 15:10:48.685280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c83ccf479d'
down_revision = '5273169ad91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempat_praktik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tempat_praktik', sa.String(length=100), nullable=False),
    sa.Column('alamat_praktik', sa.String(length=200), nullable=False),
    sa.Column('kota_praktik', sa.String(length=50), nullable=False),
    sa.Column('hari_praktik', sa.String(length=50), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempat_praktik')
    # ### end Alembic commands ###
