"""added hari_praktik

Revision ID: fad01a3fac5b
Revises: 34d19eb9e801
Create Date: 2022-08-01 22:46:20.803984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad01a3fac5b'
down_revision = '34d19eb9e801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hari_praktik', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('batas_sip', sa.DateTime(), nullable=False))
        batch_op.drop_column('batas_SIP')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_dokter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_SIP', sa.DATETIME(), nullable=False))
        batch_op.drop_column('batas_sip')
        batch_op.drop_column('hari_praktik')

    # ### end Alembic commands ###
